services:
  mysql:
    image: mysql:8.0
    container_name: ticket_sales_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ticket_sales
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 10s

volumes:
  mysql_data: