name: Test and Cleanup DCR Clients

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate SSL certificates
      run: npm run generate-ssl

    - name: Get installed Playwright version
      id: playwright-version
      run: echo "version=$(npm list --depth=0 --json | jq -r '.dependencies["@playwright/test"].version')" >> $GITHUB_OUTPUT

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps

    - name: Run OAuth tests (DCR and other OAuth features, OAuth enabled)
      run: npx playwright test --reporter=list --config=playwright-oauth.config.ts
      env:
        AUTHLETE_SERVICE_ACCESS_TOKEN: ${{ secrets.AUTHLETE_SERVICE_ACCESS_TOKEN }}
        AUTHLETE_SERVICE_ID: ${{ secrets.AUTHLETE_SERVICE_ID }}
        AUTHLETE_BASE_URL: ${{ secrets.AUTHLETE_BASE_URL }}
        ORGANIZATION_ACCESS_TOKEN: ${{ secrets.ORGANIZATION_ACCESS_TOKEN }}
        CI: true

    - name: Run MCP tests (OAuth disabled)
      run: npx playwright test --reporter=list --config=playwright-mcp.config.ts
      env:
        AUTHLETE_SERVICE_ACCESS_TOKEN: ${{ secrets.AUTHLETE_SERVICE_ACCESS_TOKEN }}
        AUTHLETE_SERVICE_ID: ${{ secrets.AUTHLETE_SERVICE_ID }}
        AUTHLETE_BASE_URL: ${{ secrets.AUTHLETE_BASE_URL }}
        ORGANIZATION_ACCESS_TOKEN: ${{ secrets.ORGANIZATION_ACCESS_TOKEN }}
        CI: true

    - name: Run main app tests (OAuth disabled, excluding OAuth/MCP)
      run: npx playwright test --reporter=list
      env:
        AUTHLETE_SERVICE_ACCESS_TOKEN: ${{ secrets.AUTHLETE_SERVICE_ACCESS_TOKEN }}
        AUTHLETE_SERVICE_ID: ${{ secrets.AUTHLETE_SERVICE_ID }}
        AUTHLETE_BASE_URL: ${{ secrets.AUTHLETE_BASE_URL }}
        ORGANIZATION_ACCESS_TOKEN: ${{ secrets.ORGANIZATION_ACCESS_TOKEN }}
        CI: true

    - name: Cleanup DCR clients (always run)
      if: always()  # テストが失敗しても実行
      run: npm run cleanup:dcr:force
      env:
        AUTHLETE_SERVICE_ACCESS_TOKEN: ${{ secrets.AUTHLETE_SERVICE_ACCESS_TOKEN }}
        AUTHLETE_SERVICE_ID: ${{ secrets.AUTHLETE_SERVICE_ID }}
        AUTHLETE_BASE_URL: ${{ secrets.AUTHLETE_BASE_URL }}
        ORGANIZATION_ACCESS_TOKEN: ${{ secrets.ORGANIZATION_ACCESS_TOKEN }}
        CI: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30